version: "3.1"

services:
  jsbackend:
    image: jsbackend
    ports: 
      - 3000:3000
    environment: 
      - MONGO_HOST
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_DB
      - REDIS_HOST
      - HERE_API_KEY
      - MAPBOX_API_KEY
      - OPENCAGE_API_KEY
    depends_on: 
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: redis
    ports:
      - 6379:6379
